### ISSUE TITLE
Get a list of environments that the user has setup in the LZ

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#17] opened 2020-03-18 13:15 UTC
getEnvrionments()  - Get a list of environments that the user has setup in the LZ

**Comment by Salles-FA** [comment] 2020-05-08 19:54
tranquilitybase-io/TranquilityBase#17
tranquilitybase-io/TranquilityBase#24

**Comment by karwootang-gft** [comment] 2020-05-14 09:25
@sunderhill-gft, @Salles-FA, This looks like a dupe of:
https://github.com/tranquilitybase-io/tb-houston-service/issues/84

I will close if no objections.

**Comment by Salles-FA** [comment] 2020-05-14 11:56
Hi @karwootang-gft,

by closing this we need to open a new issue to make new end points and change the DB structure for these UI implementation:
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/71
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/66

It could be one issue for each new set of EndPoint (PUSH, GET, PUT, etc...):
- Environments
- LAN VPC
- Folder Structure

**Comment by karwootang-gft** [comment] 2020-05-20 12:33
Hi Fabio @Salles-FA - lzmetadata endpoints have been created, can we close this issue now?

**Closed** 2020-05-20 13:19 UTC
Labels: dac
